import { z } from 'zod'
import { MAX_STAMPS_PER_SCAN } from '../constants'
import { publicTokenSchema } from './common'

/** Sources that can add a stamp, used for auditing and per-source limits. */
export const STAMP_SOURCES = [
  'staff_scan',
  'kiosk',
  'manual',
  'import',
  'campaign',
  'signup_bonus',
] as const
export type StampSource = (typeof STAMP_SOURCES)[number]

/**
 * The scan endpoint. `idempotencyKey` is generated by the scanner (one per scan
 * attempt) so a retry — or the offline queue flushing twice — never double-stamps.
 */
export const stampSchema = z.object({
  cardToken: publicTokenSchema,
  count: z.number().int().min(1).max(MAX_STAMPS_PER_SCAN).default(1),
  locationId: z.string().uuid().optional(),
  idempotencyKey: z.string().min(8).max(80),
  /** Minor units, required when the card's rule mode is `min_spend`. */
  purchaseAmount: z.number().int().min(0).optional(),
  /** Set when the scan happened offline, so analytics use the real moment. */
  occurredAt: z.coerce.date().optional(),
  note: z.string().trim().max(200).optional(),
})
export type StampInput = z.infer<typeof stampSchema>

export const stampResultSchema = z.object({
  customerCardId: z.string().uuid(),
  stampsAdded: z.number().int(),
  stampsCount: z.number().int(),
  stampsRequired: z.number().int(),
  cycleIndex: z.number().int(),
  /** Rewards unlocked by this scan. */
  unlockedRewards: z.array(
    z.object({
      grantId: z.string().uuid(),
      title: z.string(),
      description: z.string(),
      code: z.string(),
      expiresAt: z.coerce.date().nullable(),
    }),
  ),
  /** Rewards already waiting to be claimed, unlocked earlier. */
  pendingRewards: z.array(
    z.object({ grantId: z.string().uuid(), title: z.string(), code: z.string() }),
  ),
  customer: z.object({ id: z.string().uuid(), firstName: z.string(), isNew: z.boolean() }),
  /** True when the request replayed a previously-applied idempotency key. */
  replayed: z.boolean(),
})
export type StampResult = z.infer<typeof stampResultSchema>

export const redeemSchema = z
  .object({
    grantId: z.string().uuid().optional(),
    /** Staff can type the short code instead of scanning. */
    code: z.string().trim().min(4).max(12).optional(),
    cardToken: publicTokenSchema.optional(),
    locationId: z.string().uuid().optional(),
    idempotencyKey: z.string().min(8).max(80),
  })
  .refine((input) => Boolean(input.grantId || input.code || input.cardToken), {
    message: 'grant_reference_required',
  })
export type RedeemInput = z.infer<typeof redeemSchema>

/** Manual adjustment from the dashboard (corrections, goodwill). Always audited. */
export const adjustStampsSchema = z.object({
  customerCardId: z.string().uuid(),
  delta: z
    .number()
    .int()
    .min(-20)
    .max(20)
    .refine((value) => value !== 0, 'delta_required'),
  reason: z.string().trim().min(3).max(200),
  idempotencyKey: z.string().min(8).max(80),
})

/** Kiosk: the screen holds a session, and rotates a single-use nonce into its QR. */
export const kioskSessionSchema = z.object({
  cardId: z.string().uuid(),
  locationId: z.string().uuid(),
  deviceLabel: z.string().trim().max(60).optional(),
})

export const kioskStampSchema = z.object({
  nonce: z.string().min(16).max(120),
  cardToken: publicTokenSchema,
  idempotencyKey: z.string().min(8).max(80),
})

/** Public view of a customer's card, rendered by the `pass` app and the wallet pass. */
export const publicCardStateSchema = z.object({
  token: z.string(),
  business: z.object({
    name: z.string(),
    slug: z.string(),
    logoUrl: z.string().nullable(),
    locations: z.array(
      z.object({
        name: z.string(),
        address: z.string().nullable(),
        mapsUrl: z.string().nullable(),
      }),
    ),
  }),
  card: z.object({
    id: z.string().uuid(),
    name: z.string(),
    stampsRequired: z.number().int(),
    design: z.record(z.string(), z.unknown()),
    terms: z.string(),
  }),
  stampsCount: z.number().int(),
  cycleIndex: z.number().int(),
  nextReward: z
    .object({ atStamp: z.number().int(), title: z.string(), description: z.string() })
    .nullable(),
  rewards: z.array(
    z.object({ atStamp: z.number().int(), title: z.string(), description: z.string() }),
  ),
  pendingRewards: z.array(
    z.object({
      grantId: z.string().uuid(),
      title: z.string(),
      description: z.string(),
      code: z.string(),
      expiresAt: z.coerce.date().nullable(),
    }),
  ),
  /** Active campaign offer overlaid on the card, if any. */
  activeOffer: z
    .object({ title: z.string(), description: z.string(), endsAt: z.coerce.date() })
    .nullable(),
  walletPasses: z.object({ appleUrl: z.string().nullable(), googleUrl: z.string().nullable() }),
  lastStampAt: z.coerce.date().nullable(),
})
export type PublicCardState = z.infer<typeof publicCardStateSchema>
